### ISSUE TITLE
screen capture problem

### ISSUE THREAD

**Issue by MadKing-maker** [karma22/Artco#1]
as I show to Miss Choi the when we done the screen capture ,the save pass can not found the video

**Comment by karma22** [comment]
what does 'save pass' mean? save path?
can you check to be installed 'Setup Screen Capturer Recorder v0.12.10' in control panel?

**Comment by MadKing-maker** [comment]
Save path&nbsp;







------------------ Original ------------------

**Comment by karma22** [comment]
[https://github.com/karma22/Artco/commit/229245611759d147d8e7a442bdfc5500bb11b3fc](url)
